" jasmith79's .vimrc

" we'll add a plugin instead of the standard modeline
set nomodeline
set encoding=utf8
filetype plugin indent on

" be sure to use vim instead of vi settings
set nocompatible

" allow backspacing over everything in insert mode
set backspace=indent,eol,start

" highlights matching [({
set showmatch

" autoreload when something else changes the file
set autoread

" make the search ignore case unless caps are present
set ignorecase
set smartcase

" don't redraw during macros
set lazyredraw

" mice and men
if has('mouse')
  set mouse=a
endif

syntax on

" use system clipboard. On windows should be unnamed instead of unnamedplus
set clipboard=unnamedplus

" change the default splitting behavior to something more sensible
set splitbelow
set splitright

" ensures that editing a new buffer doesn't close the current one
set hidden

" tabs are icky, set to 2 spaces
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab

" mind in the gutter
set number

set cmdheight=2

inoremap fp <ESC>
let mapleader="\<SPACE>"

" Remap cursor movement for colemak, l is fine as is.
nnoremap j h
nnoremap h k
nnoremap k j
vnoremap j h
vnoremap h k
vnoremap k j

" Arrows to no-op
nnoremap <Left> <Nop>
nnoremap <Up> <Nop>
nnoremap <Down> <Nop>
nnoremap <Right> <Nop>

vnoremap <Left> <Nop>
vnoremap <Up> <Nop>
vnoremap <Down> <Nop>
vnoremap <Right> <Nop>

" vim-airline
let g:airline#extensions#tabline#enabled=1
set laststatus=2

" You're the One Neo...
if has("nvim")
  let &runtimepath.=','
endif
