#!/bin/bash

if command -v cmus >/dev/null; then
  cmus-remote --stop
  cmus-remote -c 
  cmus-remote -P -c
  cmus-remote -q -c
  cmus-remote -P "$1"
  cmus-remote --next
  sleep 0.1
  cmus-remote -p
else
  echo "cmus not installed. Use e.g. sudo apt install cmus"
fi
