#!/usr/bin/env bash
# Determines OS and in the case of Ubuntu variants version.

os=$(uname)
if [[ "$os" =~ [Dd]arwin ]]; then
  echo "macos"
elif [[ "$os" =~ [Ll]inux ]]; then
  distro=$(head -n 1 /etc/lsb-release | grep -o "=[a-zA-Z]\+" | cut -c2-)
  if [ "$distro" = "LinuxMint" ]; then
    ubuntu_version=$(grep -o "[0-9]\{2\}" /etc/upstream-release/lsb-release | head -n 1)
    echo "ubuntu $ubuntu_version"
  elif [ "$distro" = "Ubuntu" ]; then
    ubuntu_version=$(grep -o "[0-9]\{2\}" /etc/lsb-release | head -n 1)
    echo "ubuntu $ubuntu_version"
  else
    echo "$distro"
  fi
else
  echo "Unknown platform. Aborting!" >&2
  exit 1
fi

# get-platform () {
#   if [[ "$os" =~ [Dd]arwin ]]; then
#     echo "macos"
#   elif [[ "$os" =~ [Ll]inux ]]; then
#     distro=$(head -n 1 /etc/lsb-release | grep -o "=[a-zA-Z]\+" | cut -c2-)
#     if [ "$distro" = "LinuxMint" ]; then
#       ubuntu_version=$(grep -o "[0-9]\{2\}" /etc/upstream-release/lsb-release | head -n 1)
#       echo "ubuntu $ubuntu_version"
#     elif [ "$distro" = "Ubuntu" ]; then
#       ubuntu_version=$(grep -o "[0-9]\{2\}" /etc/lsb-release | head -n 1)
#       echo "ubuntu $ubuntu_version"
#     else
#       echo "$distro"
#     fi
#   else
#     echo "Unknown platform. Aborting!" >&2
#     exit 1
#   fi
# }
