return {
	"nvim-treesitter/nvim-treesitter",
	branch = "main",
	build = ":TSUpdate",
	config = function()
		require("nvim-treesitter").setup({
			highlight = { enable = true },
			ensure_installed = {
				-- I don't have a problem.
				-- Oh, you didn't say I had a problem?
				-- Good, 'cause I don't have one.
				"c",
				"toml",
				"svelte",
				"glsl",
				"dockerfile",
				"yaml",
				"jsonc",
				"json",
				"hjson",
				"ninja",
				"cmake",
				"make",
				"go",
				"graphql",
				"ruby",
				"http",
				"prisma",
				"php",
				"java",
				"kotlin",
				"css",
				"scss",
				"elixir",
				"ocaml",
				"cpp",
				"swift",
				"javascript",
				"typescript",
				"html",
				"tsx",
				"bash",
				"markdown",
				"clojure",
				"fennel",
				"haskell",
				"rust",
				"dot",
				"hcl",
				"diff",
				"luadoc",
				"vim",
				"vimdoc",
			},
		})
	end,
}
